tags:
- name: auth
  description: Auth API
- name: hello
  description: Hello API

paths:
# [POST] signup
  /signup:
    post: 
      tags:
      - auth
      summary: Create a new user. Role - admin / customer
      parameters: 
      - name: signup
        in: body
        description: User Email
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Internal Server Error'
# [POST] signin
  /signin: 
    post: 
      tags:
      - auth
      summary: Login user
      parameters: 
      - name: signin
        in: body
        description: User Email
        required: true
        schema:
          $ref: '#/definitions/login_user'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        401:
          description: 'Unauthorize'
        409:
          description: 'Conflict'
        500:
          description: 'Internal Server Error'
# [POST] logout
  /logout: 
    post: 
      tags:
      - auth
      summary: Logout user
      responses:
        200:
          description: 'OK'
        401:
          description: 'Unauthorize'
        500:
          description: 'Internal Server Error'
# [GET] hello world
  /hello-world:
    get:
      tags:
      - hello
      summary: Get hello world
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        401:
          description: 'Unauthorize'
        403: 
          description: 'Forbidden'
        500:
          description: 'Server Error'

# [GET] admin hello world
  /admin/hello-world:
    get:
      tags:
      - hello
      summary: Get hello world
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        401:
          description: 'Unauthorize'
        403: 
          description: 'Forbidden'
        500:
          description: 'Server Error'

# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
        - role
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
      role: 
        type: string
        description: user role
  login_user:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

schemes:
 - https
 - http
